services:
  neo4j:
    image: neo4j:5.19
    ports:
      - "7687:7687"
      - "7474:7474"
    environment:
      - NEO4J_AUTH=none
      - NEO4J_PLUGINS=["apoc"]
    volumes:
      - ./neo4j/data:/data